# bookings_service/app/constants/menu_items.py

MENU_ITEMS = {
    "hudson_valley_cheese_board": {
        "name": "Hudson Valley Cheese Board",
        "category": "starter",
        "description": "Cypress Hill Farms blue cheese, Murray’s Farms young gouda, Grafton Farms aged cheddar, hard salami, dried fruit, olives, crostini.",
        "price_cents": 2400,
        "dietary_restrictions": [],
        "is_active": True,
    },
    "burrata": {
        "name": "Burrata",
        "category": "starter",
        "description": "Tomato confit, olive oil, roasted garlic, cracked fresh pepper. Served with crostini or gluten-free crackers.",
        "price_cents": 2000,
        "dietary_restrictions": ["vegetarian"],
        "is_active": True,
    },
    "jumbo_bavarian_pretzel": {
        "name": "Jumbo Bavarian Pretzel",
        "category": "starter",
        "description": "Butter brushed, sea salt, honey dijon.",
        "price_cents": 1400,
        "dietary_restrictions": ["vegetarian"],
        "is_active": True,
    },
    "mezze_platter": {
        "name": "Mezze Platter",
        "category": "starter",
        "description": "Grilled soft flatbread, sun-dried tomato hummus, stuffed grape leaves, marinated olives, feta cheese.",
        "price_cents": 1900,
        "dietary_restrictions": ["vegetarian"],
        "is_active": True,
    },
    "create_your_own_salad_or_bowl": {
        "name": "Create Your Own Salad or Bowl",
        "category": "salad_bowl",
        "description": "Choose greens, grains, proteins, vegetables, fruits, cheeses, and dressing. Greens sourced from Satur Farm, Norwich Meadows Farm, and Hepworth Farm.",
        "price_cents": 1600,
        "dietary_restrictions": [],
        "is_active": True,
    },
    "add_grilled_chicken": {
        "name": "Add Grilled Chicken",
        "category": "add_on",
        "description": "Protein add-on for salads/bowls.",
        "price_cents": 700,
        "dietary_restrictions": ["gluten_free", "dairy_free"],
        "is_active": True,
    },
    "add_grilled_salmon": {
        "name": "Add Grilled Salmon",
        "category": "add_on",
        "description": "Protein add-on for salads/bowls.",
        "price_cents": 900,
        "dietary_restrictions": ["gluten_free", "dairy_free"],
        "is_active": True,
    },
    "add_grilled_tuna": {
        "name": "Add Grilled Tuna",
        "category": "add_on",
        "description": "Protein add-on for salads/bowls.",
        "price_cents": 1000,
        "dietary_restrictions": ["gluten_free", "dairy_free"],
        "is_active": True,
    },
    "add_fried_falafel": {
        "name": "Add Fried Falafel",
        "category": "add_on",
        "description": "Protein add-on for salads/bowls.",
        "price_cents": 700,
        "dietary_restrictions": ["vegetarian"],
        "is_active": True,
    },
    "add_hard_boiled_egg": {
        "name": "Add Hard Boiled Egg",
        "category": "add_on",
        "description": "Protein add-on for salads/bowls.",
        "price_cents": 300,
        "dietary_restrictions": ["gluten_free", "vegetarian"],
        "is_active": True,
    },
    "add_bacon": {
        "name": "Add Bacon",
        "category": "add_on",
        "description": "Protein add-on for salads/bowls.",
        "price_cents": 400,
        "dietary_restrictions": ["gluten_free", "dairy_free"],
        "is_active": True,
    },
    "classic_chicken_salad": {
        "name": "Classic Chicken Salad",
        "category": "sandwich",
        "description": "Herb mayonnaise. Served on Martin’s bun or whole wheat wrap.",
        "price_cents": 1800,
        "dietary_restrictions": ["gluten_free"],
        "is_active": True,
    },
    "free_range_turkey_club": {
        "name": "Free Range Turkey Club",
        "category": "sandwich",
        "description": "Bacon, lettuce, tomato chutney, sliced tomato, stone ground wheat bread.",
        "price_cents": 2100,
        "dietary_restrictions": [],
        "is_active": True,
    },
    "fried_chicken_sandwich": {
        "name": "Fried Chicken Sandwich",
        "category": "sandwich",
        "description": "Fried chicken thigh on Martin’s roll with hot honey, house-made pickles, and coleslaw.",
        "price_cents": 2000,
        "dietary_restrictions": [],
        "is_active": True,
    },
    "angus_beef_hamburger": {
        "name": "Angus Beef Hamburger",
        "category": "sandwich",
        "description": "Fresh off the grill. Gluten-free bread available upon request.",
        "price_cents": 1900,
        "dietary_restrictions": [],
        "is_active": True,
    },
    "turkey_burger": {
        "name": "Turkey Burger",
        "category": "sandwich",
        "description": "Fresh off the grill. Gluten-free bread available upon request.",
        "price_cents": 1900,
        "dietary_restrictions": [],
        "is_active": True,
    },
    "grilled_salmon_sandwich_style": {
        "name": "Grilled Salmon (Sandwich Style)",
        "category": "sandwich",
        "description": "Fresh off the grill. Gluten-free bread available upon request.",
        "price_cents": 2200,
        "dietary_restrictions": ["dairy_free"],
        "is_active": True,
    },
    "grilled_chicken_breast_sandwich_style": {
        "name": "Grilled Chicken Breast (Sandwich Style)",
        "category": "sandwich",
        "description": "Fresh off the grill. Gluten-free bread available upon request.",
        "price_cents": 1900,
        "dietary_restrictions": ["dairy_free"],
        "is_active": True,
    },
    "beyond_burger": {
        "name": "Beyond Burger",
        "category": "sandwich",
        "description": "Plant-based burger. Gluten-free bread available upon request.",
        "price_cents": 2000,
        "dietary_restrictions": ["vegan", "vegetarian", "dairy_free"],
        "is_active": True,
    },
    "quesadilla_chicken": {
        "name": "Quesadilla (Chicken)",
        "category": "sandwich",
        "description": "Cheddar melted in a flour tortilla. Served with pico de gallo.",
        "price_cents": 1700,
        "dietary_restrictions": [],
        "is_active": True,
    },
    "quesadilla_cheese": {
        "name": "Quesadilla (Cheese)",
        "category": "sandwich",
        "description": "Cheddar melted in a flour tortilla. Served with pico de gallo.",
        "price_cents": 1500,
        "dietary_restrictions": ["vegetarian"],
        "is_active": True,
    },
    "all_beef_hot_dog": {
        "name": "All-Beef Hot Dog",
        "category": "sandwich",
        "description": "All-beef hot dog on Martin’s bun. Optional cheddar or American cheese.",
        "price_cents": 1400,
        "dietary_restrictions": [],
        "is_active": True,
    },
    "hot_dog_add_cheese": {
        "name": "Hot Dog — Add Cheese",
        "category": "add_on",
        "description": "Add cheddar or American cheese.",
        "price_cents": 200,
        "dietary_restrictions": ["vegetarian"],
        "is_active": True,
    },
    "lobster_roll": {
        "name": "Lobster Roll",
        "category": "sandwich",
        "description": "Lobster salad on a toasted buttered roll, lemon aioli, and a lemon wedge.",
        "price_cents": 3400,
        "dietary_restrictions": [],
        "is_active": True,
    },
    "pizza_flatbread": {
        "name": "Pizza Flatbread",
        "category": "sandwich",
        "description": "San Marzano tomato sauce, fresh mozzarella, basil.",
        "price_cents": 1800,
        "dietary_restrictions": ["vegetarian"],
        "is_active": True,
    },
    "grilled_strip_steak_dinner_only": {
        "name": "Grilled Strip Steak (Dinner Only)",
        "category": "entree",
        "description": "Grilled NY strip steak, wild mushroom haricot verts, and a baked potato with sour cream and chopped chives.",
        "price_cents": 4200,
        "dietary_restrictions": [],
        "is_active": True,
    },
    "classic_potato_salad": {
        "name": "Classic Potato Salad",
        "category": "side",
        "description": "Grill side.",
        "price_cents": 900,
        "dietary_restrictions": ["vegetarian", "gluten_free"],
        "is_active": True,
    },
    "baked_potato": {
        "name": "Baked Potato",
        "category": "side",
        "description": "With sour cream and butter.",
        "price_cents": 900,
        "dietary_restrictions": ["vegetarian", "gluten_free"],
        "is_active": True,
    },
    "grilled_vegetable_medley": {
        "name": "Grilled Vegetable Medley",
        "category": "side",
        "description": "Grill side.",
        "price_cents": 1100,
        "dietary_restrictions": ["vegan", "vegetarian", "gluten_free", "dairy_free"],
        "is_active": True,
    },
    "potato_chips": {
        "name": "Potato Chips",
        "category": "side",
        "description": "Grill side.",
        "price_cents": 600,
        "dietary_restrictions": ["vegan", "vegetarian", "gluten_free", "dairy_free"],
        "is_active": True,
    },
    "grilled_chicken_strips": {
        "name": "Grilled Chicken Strips",
        "category": "kids",
        "description": "Kids option.",
        "price_cents": 1100,
        "dietary_restrictions": ["gluten_free", "dairy_free"],
        "is_active": True,
    },
    "mac_and_cheese": {
        "name": "Mac & Cheese",
        "category": "kids",
        "description": "Kids option (GF).",
        "price_cents": 1200,
        "dietary_restrictions": ["gluten_free", "vegetarian"],
        "is_active": True,
    },
    "classic_pound_cake": {
        "name": "Classic Pound Cake",
        "category": "dessert",
        "description": "With a vanilla glaze.",
        "price_cents": 900,
        "dietary_restrictions": ["vegetarian"],
        "is_active": True,
    },
    "blondies": {
        "name": "Blondies",
        "category": "dessert",
        "description": "From the bake shop.",
        "price_cents": 800,
        "dietary_restrictions": ["vegetarian"],
        "is_active": True,
    },
    "churros": {
        "name": "Churros",
        "category": "dessert",
        "description": "Rolled in cinnamon sugar and served with chocolate chili sauce.",
        "price_cents": 1000,
        "dietary_restrictions": ["vegetarian"],
        "is_active": True,
    },
    "fudge_brownies": {
        "name": "Fudge Brownies",
        "category": "dessert",
        "description": "From the bake shop.",
        "price_cents": 800,
        "dietary_restrictions": ["vegetarian"],
        "is_active": True,
    },
    "oatmeal_and_chocolate_chip_cookies": {
        "name": "Oatmeal & Chocolate Chip Cookies",
        "category": "dessert",
        "description": "From the bake shop.",
        "price_cents": 600,
        "dietary_restrictions": ["vegetarian"],
        "is_active": True,
    },
    "ice_cream_sundae_bar": {
        "name": "Ice Cream Sundae Bar",
        "category": "dessert",
        "description": "Vanilla, chocolate, strawberry, coffee, soy-based, coconut (DF). Includes topping bar.",
        "price_cents": 1200,
        "dietary_restrictions": ["vegetarian"],
        "is_active": True,
    },
    "popsicle_strawberry": {
        "name": "Popsicle — Strawberry",
        "category": "dessert",
        "description": "Vegan, dairy free.",
        "price_cents": 500,
        "dietary_restrictions": ["vegan", "vegetarian", "dairy_free", "gluten_free"],
        "is_active": True,
    },
    "popsicle_tangerine": {
        "name": "Popsicle — Tangerine",
        "category": "dessert",
        "description": "Vegan, dairy free.",
        "price_cents": 500,
        "dietary_restrictions": ["vegan", "vegetarian", "dairy_free", "gluten_free"],
        "is_active": True,
    },
    "popsicle_raspberry": {
        "name": "Popsicle — Raspberry",
        "category": "dessert",
        "description": "Vegan, dairy free.",
        "price_cents": 500,
        "dietary_restrictions": ["vegan", "vegetarian", "dairy_free", "gluten_free"],
        "is_active": True,
    },
}